### ISSUE TITLE
unicornhatHD not supported

### ISSUE THREAD

**Issue by yratof** [SeanCline/UnicornHatWeather#1]
Any chance for updating using it?

**Comment by SeanCline** [comment]
The work to support the HD is already mostly done in a separate [Gif2UnicornHat branch](https://github.com/SeanCline/Gif2UnicornHat/tree/UnicornHatHd).

Two things held me up from merging:
1) It turn out there's no way to automatically detect which hat is installed. The regular 8x8 UnicornHat has an identification eeprom, [but the HD doesn't](https://github.com/pimoroni/unicorn-hat-hd/issues/47). So, we'll need a command line option in Gif2UnicornHat, and a setting in UnicornHatWeather.
2) The WS2812b driver for the UnicornHat needs root to run since it uses DMA, but the SPI driver for the UnicornHatHd got angry when running as root. Not a huge deal, but it's certainly a gotcha.

**Comment by SeanCline** [comment]
Alright, Unicorn HAT HD support should be added. Make sure you re-pull, and re-build everything (as described in [readme.md](https://github.com/SeanCline/UnicornHatWeather/blob/master/README.md)) to make sure you pick up all the submodule changes.

Now, you can specify `'Unicorn HAT HD'` as the device [in config.py](https://github.com/SeanCline/UnicornHatWeather/blob/226e97ece00b9af124235b999249ef60e04511de/config.py#L22). You'll also probably have to raise the brightness in config.py to something closer to `.20`, since the HD is a bit dimmer.

Along with the caveats above, the gifs in this repo are still 8x8px. Gif2UnicornHat will do pixel-doubling to upscale to 16x16 on the HD. 16x16 images should work though, if you replace the files on disk. If you do make some, I'd like to see them. 🙂

![PXL_20230704_162254258 MP](https://github.com/SeanCline/UnicornHatWeather/assets/3418587/f8bd5186-726d-402c-9927-8a2476b85c0d)
![PXL_20230704_162811609 MP](https://github.com/SeanCline/UnicornHatWeather/assets/3418587/c8ad982c-2659-448c-8231-185902304a01)

**Comment by yratof** [comment]
Stunning. I'll create some icons and and make a pull request this week :)
